### PR TITLE
feat(nestjs): added page number option

### PR DESCRIPTION
**Pull request by spencercap**
added a feature for specifying the page number you want from the whosampled search. 

usage, just add the page number you want to end of the route: 
`http://localhost:3000/artist/2pac/2`

---
FYI - this builds off of the header User-Agent fix in https://github.com/thulioph/whosampled-scraper/pull/12

### CODE REVIEW

**Comment by spencercap** [comment]
@thulioph 🛎 bump

**Comment by thulioph** [comment]
Thank you @spencercap. Can you update your PR, please? After the merge of the other PR there are small conflicts to fix.

**Comment by spencercap** [comment]
there ya go @thulioph 👍

**Comment by thulioph** [comment]
Thank you @spencercap 🤖

**Pull request merged**
